language: python

dist: xenial
sudo: required

git:
  depth: 1000

env:
  global:
    - PANDAS=pandas
    - COVERAGE=true
    - SKIPSLOW=""
    - DOCTR_PUSH_TYPE=""
    - XARRAY=
    - OPENBLAS=0
    - USE_PYPI=false
    - PYTHONHASHSEED=0
    - MKL_NUM_THREADS=1
    - OPENBLAS_NUM_THREADS=1
    - OMP_NUM_THREADS=1
    - PIP_PACKAGES=
    - secure: "aCm98s/mNxRSoTEhpIgfvRKzzJKdDkm/9TufIvgWvnkeiyDQqZwoqRVDIikZ+v6mkFeu7dr7BBojyPXnhkhji+SkNFz5ArtEqahJTvIZhP2nWgktlQSWkaC2Q5GyCWPhdQag/ImYbM4RK1WvtIVcSL7GPL0jLTgFDXY6/Hdl0eQY7kfWtojxIZUJShxn9IPfXE3gGQeWHEOL7SkZ3+8KxBJAUzrdd9J32PiHWZb5BcUupTQcW29ajoco4q1fdL/xPu3GZnys8EClorHxnPptQWfGGlnoJ79Q6H7Jhw6BGIj2fDCG9qX4boEH2zvH8ZKlbuTvMeVcBiLxPE8BpRmx2drX2kDyUo5ywVwA0W/7zsZ2YUYEyHEYL+cr4WVFdoDpwwPKaHOTp8F4Q+lQgkvxZbSlO6dUEMLNxnltgujAAdiaRJKLd2CwA85RjqYGLkMzTqBgYhH+p+7wB6jK8EJgoqxU3k98LfaeqyhsPrdWsxVLleLVAvzhXpNilQfX4NBPf+DYsn9NeyXYzp85H9p+J8DGJMJ42kBdP1r/cz1Y44SrGZhlk1MhLhb+uX7kV7nnmcW87NYoGSr52S5vNVL9iSU980SzJ08wOZwxwkKXOqgEJtMqdHsEuqY9jSQ2m/xAdarpxBsDD+Pw2gPfar+R8Lcptep50pMPFMgddDWV2f4="

matrix:
  fast_finish: true
  include:
  - python: 3.5
    env:
    - PYTHON=3.5
    - NUMPY=1.13
    - SCIPY=0.19
    - PANDAS=0.20
    - STATSMODELS=0.8
  - python: 3.6
    env:
    - PYTHON=3.6.7
    - NUMPY=1.13
    - SCIPY=1.0
    - PANDAS=0.21
    - XARRAY=0.9
    - STATSMODELS=0.8
  - python: 3.6
    env:
    - PYTHON=3.6.7
    - NUMPY=1.14
    - SCIPY=1
    - PANDAS=0.22
    - XARRAY=0.10
    - STATSMODELS=0.9
    - PIP_PACKAGES="xxhash"
  - python: 3.7
    env:
    - PYTHON=3.7
    - NUMPY=1.15
    - SCIPY=1.1
    - PANDAS=0.23
    - XARRAY=0.10
    - STATSMODELS=0.9
    - OPENBLAS=1
  - python: 3.7
    env:
    - PYTHON=3.7
    - USE_PYPI=true
    - XARRAY=0.11
    - DOCBUILD=true
    - PIP_PACKAGES="xxhash"

before_install:
  - sudo apt-get install -y pandoc enchant
  - git fetch --tags
  - wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda3.sh -nv
  - chmod +x miniconda3.sh
  - ./miniconda3.sh -b
  - export PATH=/home/travis/miniconda3/bin:$PATH
  - conda config --set always_yes true
  - conda update --all -q
  # Install packages
  - |
    if [[ ${USE_PYPI} = true ]]; then
      source ci/install-from-pypi.sh
    else
      source ci/install-from-conda.sh
    fi;
  - source ci/install-common.sh
  - pip list

install:
  - python setup.py develop

script:
  - pytest -n 2 --cov-config .coveragerc --cov=linearmodels linearmodels --durations=10 ${SKIPSLOW}
  - flake8 linearmodels
  - set -e
  - |
    if [[ ${DOCBUILD} = true ]]; then
      sudo apt-get install -y enchant
      pip install sphinxcontrib-spelling
      pip list
      cd doc
      make html
      make html
      make spelling
      cd ..
      doctr deploy devel --build-tags
      if [[ -z ${TRAVIS_TAG} ]]; then
        echo "Not a tagged build."
      else
        doctr deploy . --build-tags
      fi
    fi

after_success:
  - if [ ${COVERAGE} = true ]; then codecov; fi
